name: Testing Auth on Python Script

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setting up APIs
        run: pip3 install google-api-python-client oauth2client

      - name: Run test script
        env:
          APP_CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS }}
          APP_PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          ANDROID_PUBLISHER: ${{ secrets.ANDROID_PUBLISHER }}
        run: |
          echo $APP_CLIENT_SECRETS > client_secrets.json
          echo $ANDROID_PUBLISHER > androidpublisher.dat
          python3 google_api_test.py $APP_PACKAGE_NAME
