name: Release Workflow

on:
  workflow_run:
    workflows: tag_workflow.yml
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Setting up Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setting up APIs
        run: pip3 install google-api-python-client oauth2client

      - name: Grant gradlew permissions
        run: chmod +x gradlew

      - name: Decode google-services.json
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        run: echo $GOOGLE_JSON > app/google-services.json

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build release apk
        env:
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_STORE_KEY_ALIAS: ${{ secrets.ANDROID_STORE_KEY_ALIAS }}
          ANDROID_STORE_KEY_PASSWORD: ${{ secrets.ANDROID_STORE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK
        env:
          APP_RELEASE_OUTPUT_PATH: ${{ secrets.RELEASE_OUTPUT_PATH }}
          APP_PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS }}
          ANDROID_PUBLISHER: ${{ secrets.ANDROID_PUBLISHER }}
        run: |
          echo $CLIENT_SECRETS > client_secrets.json
          echo $ANDROID_PUBLISHER > androidpublisher.dat
          python3 upload_app.py $APP_PACKAGE_NAME $APP_RELEASE_OUTPUT_PATH

