name: Version Increment Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.BOT_TOKEN_API }}

      - name: Setting up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Increment version
        env:
          VERSION_TAG: ${{GITHUB_REF#refs/tags/}}
        run: |
          python3 increment_version.py

      - name: Commit version update
        run: |
          git config --global user.name ${{ secrets.BOT_NAME }}
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git add .
          git commit -am "Incrementing version"
          git push
